[IV-23-24] Objetivo 2
carlosservi/Asistente_Ruta_Camioneros pull request #13
Opened 2023-10-06 08:00 UTC by pluque01

Closes #12

2023-10-06 08:01 UTC, pluque01 commented
Cuando puedas por favor asigna un milestone a este pull request y añade la etiqueta del hacktoberfest. !Gracias! :))

2023-10-06 08:09 UTC, carlosservi commented
Hecho :+1:

2023-10-13 17:23 UTC, pluque01 commented
Hola @carlosservi!
He creado las entidades mínimas que creo son necesarias para el proyecto, cuando puedas le echas un vistazo y me comentas tu opinión.
Un saludo :))

2023-10-13 17:55 UTC, carlosservi commented
Hola @pluque01 voy a revisarlo y te digo, una cosilla, tienes que crear los issues para que los commits que hagas referencien a ellos. Por lo que yo entiendo tienes que desgranar la historia de usuario haciendo varios issues que referencian a la historia de usuario e ir resolviendolos con commits. Si quieres revisalo en el guión del objetivo. Un saludo

2023-10-13 18:04 UTC, carlosservi commented
Hola @pluque01 creo que sería necesario también una clase para el chofer que se le asigna la ruta. Por otro lado no entiendo lo de la latitud del área de descanso, lo has puesto por algo en concreto?. Por lo demás lo veo genial. Un saludo y muchas gracias

2023-10-14 16:54 UTC, pluque01 commented
> Hola @pluque01 creo que sería necesario también una clase para el chofer que se le asigna la ruta.

Lo de una clase para el chofer lo estuve pensando bastante y no se me ocurría nada que fuese estrictamente necesario almacenar del mismo. ¿Qué me sugieres?

> Por otro lado no entiendo lo de la latitud del área de descanso, lo has puesto por algo en concreto?

Pues mi razonamiento fue que latitud/longitud fuesen la forma de situar una estación de servicio, pero ahora que lo pienso creo que es más simple tener una variable con los kilometros hasta la zona de descanso y ya. En el próximo commit lo modifico.

> Otra cosilla también es que nosotros no le pasamosen el constructor el StartTime ya que eso lo calcula el sistema

El StartTime que he creado es del horario de apertura; cuando abre el área de descanso. Igual el nombre de la variable es mejorable 😅

Gracias por tus comentarios @carlosservi :))

2023-10-15 14:32 UTC, carlosservi commented
Tienes razón alomejor en está HU no es necesario la parte del chofer, se puede quedar así.
La parte de la estación de servicio, yo tenía pensado almacenar los kilometros y el tiempo, si lo ves bien cambialo.
Y de lo de StartTime perdona :sweat_smile: mira lo que miré varias veces pero no caí que era la hora de apertura. Vale entonces genial, por mi lo veo bien.

2023-10-16 07:04 UTC, pluque01 commented
Cuando puedas le hechas un vistazo @carlosservi :))

2023-10-16 17:14 UTC, carlosservi commented
Si yo creo que ya está bien @pluque01, muchas gracias

2023-10-16 17:35 UTC, pluque01 commented
Pues lo único que falta es que asignes los issues #15 #14 #16 al milestone 0 @carlosservi

2023-10-19 06:40 UTC, pluque01 commented
@JJ listo para revisión aunque no estén los issues asignados al milestone aún

2023-10-19 07:08 UTC, carlosservi commented
@pluque01 Listo compañero, perdón por la tandanza.

2023-10-19 17:43 UTC, pluque01 commented
@JJ Listo para revisión; creo que he mejorado lo que me comentó en clase.

2023-10-20 05:31 UTC, JJ commented
Commits como estos [6adb674](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/13/commits/6adb6742c76878eca4e7cdcb5f4166e70ca12acd) no acaban de seguir las buenas prácticas. Quien mira el mensaje de commit tiene presente lo que se ha hecho; el mensaje debe centrarse en el por qué y en las decisiones tomadas.

2023-10-20 05:33 UTC, JJ commented
> Tienes razón alomejor en está HU no es necesario la parte del chofer, se puede quedar así.
> La parte de la estación de servicio, yo tenía pensado almacenar los kilometros y el tiempo, si lo ves bien cambialo.
> Y de lo de StartTime perdona 😅 mira lo que miré varias veces pero no caí que era la hora de apertura. Vale entonces genial, por mi lo veo bien.

El código que haga @pluque01 tiene que adaptarse a lo que está escrito en la HU, no tanto a lo que tenías pensado. Si hay alguna ambigüedad en la HU, es mejor modificarla o ampliarla; y si tanto lo que él ha pensado como lo que tú piensas soluciona el problema, es mucho menos trabajo para todos adoptar la solución que él ha desarrollado ya.

2023-10-20 05:45 UTC, JJ requested changes
Creo que ha sido, en general, bastante completo, pero hay algunos aspectos de algunos issues que deberías de analizar más detenidamente.
Mucho ánimo.

2023-10-20 05:45 UTC, JJ commented on src/route.go
> +func (r Route) Id() string {
¿Hay algo en la historia de usuario que pida estos getters? Por favor, consulta [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-c%C3%B3digo-definido)

2023-10-20 05:45 UTC, JJ commented on src/route.go
> +	StartTime string
¿La mejor forma de expresar una hora es una cadena?

2023-10-23 17:17 UTC, pluque01 commented
Hola @carlosservi!
Los cambios están listos para revisión. Lo que deberías hacer ahora es completar tu lista de comprobación y añadirla a la conversación, dar el visto bueno a los cambios y pedir la revisión al profesor.
Gracias de antemano 😁

2023-10-24 15:28 UTC, carlosservi commented
* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

Yo lo veo todo correcto @pluque01, muchas gracias por todo.
@JJ Listo para revisión.

2023-10-24 15:34 UTC, JJ commented
Si lo ves correcto, deberías aprobar, no comentar. Ahora mismo no está aprobado, me temo. Os parecerá que esto es una formalidad, pero la formalidad es esencial: si hay una herramienta que transmite un mensaje o pone un estado, hay que usarla.

2023-10-24 15:41 UTC, pluque01 commented on src/route.go
> +	StartTime string
Arreglado en 8841752

2023-10-24 15:42 UTC, pluque01 commented on src/route.go
> +func (r Route) Id() string {
Arreglado en cfa0aca

2023-10-24 17:53 UTC, JJ commented
Aparte de que tiene que aprobarse explícitamente por parte de @carlosservi , a @pluque01 comentarle que commits como este https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/13/commits/b739dabd1c23e69a2d4bb05b56c2d910d7a62dcc no deberían repetir en el mensaje lo que es evidente como lo que se ha añadido o quitado. El mensaje de commit debe aportar información a quien revisa, para eso es para lo que sirve.

2023-10-26 06:47 UTC, carlosservi approved these changes
Todo correcto.
@JJ Listo para revisión

2023-10-26 07:53 UTC, JJ approved these changes
👍

2023-10-26 08:08 UTC, merged