[IV-23-24] Objetivo 3
carlosservi/Asistente_Ruta_Camioneros pull request #23
Opened 2023-10-27 07:42 UTC by carlosservi

#Issues Solucionados
- Solucionado #19 Usado Go Modules.

##Lista de comprobación
* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-11 15:56 UTC, adelahera reviewed
Hola, soy uno de tus revisores. Entiendo que tu propuesta es empezar con makefile y task, y decidir sobre la marcha cuál te gusta más. No lo veo mala opción, pero sin embargo, debes de explicar por qué has decidido quedarte con esos 2 y no, por ejemplo, con Mage. Debes dar una explicación que sea objetiva, es decir, establecer una serie de criterios, y que sean esos criterios los que expliquen tu decisión. Te pongo en ejemplo. Si utilizas como criterio el lenguaje en el que esta escrito, y en tu caso, a lo mejor te conviene que este escrito en Go, puedes decir, voy a elegir este task runner porque cumple este criterio. En cualquier caso, creo que el principal problema es que no has dejado claro cuáles son los criterios que has seguido para elegir Make o Task.

Por otro lado, debes incluir también algo de documentación sobre el comprobador de sintaxis.

2023-11-11 15:58 UTC, adelahera commented on Taskfile.yaml
> +      - task build
¿Este comando seguro que analiza la sintaxis del texto? Lo mismo me equivoco, pero me suena un poco raro.

2023-11-12 09:45 UTC, carlosservi commented on Taskfile.yaml
> +      - task build
Hola! Gracias por la ayuda. Ya he explicado un poco mejor las decisiones en [b7ea54c](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/b7ea54ca77defe33f1a2c948c2b4d40d4c2e1d5f), si puedes dime que te parece. Por otro lado, toda la razón, era incorrecto, me equivoque al ponerlo, ya esta subsanado también en [618051a](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/618051a4c4164dcdbf1891eaba846d12b206cb65). Muchas gracias

2023-11-12 20:24 UTC, adelahera commented on Taskfile.yaml
> +      - task build
Hola de nuevo. Yo lo que haría para terminar de mejorarlo sería poner explícitamente los criterios. Hasta el momento has dado la explicación de por qué has tomado la decisión, que es coherente. Sin embargo, como te acabo de comentar, incluiría explícitamente los criterios en los que te basas para la elección.

2023-11-13 14:38 UTC, carlosservi commented on Taskfile.yaml
> +      - task build
Hola @adelahera ya he incorporado los criterios específicos que he utilizado. Solucionado en [5f8e743](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/5f8e743dca7494949892d579a9d854778a774ae4). Cuando puedas dime que te parece. Un saludo

2023-11-13 15:39 UTC, adelahera approved these changes
👍 👍

2023-11-17 08:15 UTC, JJ requested changes
O eliges uno u otro; poner dos gestores de tareas tampoco ayuda mucho. También trata de limitarte en la descripción de las herramientas a los criterios que hayas elegido.
Está muy cerca de ser alcanzado, pero te agradecería que cambiaras estas cosillas.

2023-11-17 08:15 UTC, JJ commented on README.md
> +sudo snap install task --classic
Debes intentar instalar las herramientas siempre desde un usuario no privilegiado

2023-11-17 08:15 UTC, JJ commented on README.md
> +Makefile no necesita instalación.
¿Qué quieres decir?

2023-11-17 08:15 UTC, JJ commented on README.md
> +Introduciendo make help o task help te muestra los comandos necesarios muy sencillos. Por ejemplo make build o task build compila el proyecto e ingresa el bin en la carpeta ./bin
Pero ¿cuál estás usando? En el README debes poner solo el que estés usando.

2023-11-17 08:15 UTC, JJ commented on Taskfile.yaml
> +      - task build
¿No puedes poner dependencia entre tareas?

2023-11-17 08:15 UTC, JJ commented on docs/eleccion_gestor_tareas_y_dependencias.md
> +## Criterios
Los criterios deberían ir *antes*

2023-11-17 08:15 UTC, JJ commented on iv.yaml
> +  tareas:
Esto no tienes que ponerlo aquí.

2023-11-17 08:43 UTC, carlosservi commented on iv.yaml
> +  tareas:
Solucionado en [0c92cd1](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/0c92cd128d41ff0ecd36b18740ece625b6b4960b)

2023-11-17 08:45 UTC, carlosservi commented on docs/eleccion_gestor_tareas_y_dependencias.md
> +## Criterios
Solucionado en [a5afe04](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/a5afe04c74c8fbc92d8c6fd4fa75e430a17676ad)

2023-11-17 08:51 UTC, carlosservi commented on Taskfile.yaml
> +      - task build
[94559e2](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/94559e2501aeaa97b3aff6cb70b9fb90fd075a48)

2023-11-17 08:55 UTC, carlosservi commented on README.md
> +sudo snap install task --classic
Solucionado en [5463cd0](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/5463cd0b9d37479e511e9cd598c8e5adb9b6a80d)

2023-11-17 08:55 UTC, carlosservi commented on README.md
> +Makefile no necesita instalación.
Solucionado en [5463cd0](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/5463cd0b9d37479e511e9cd598c8e5adb9b6a80d)

2023-11-17 08:55 UTC, carlosservi commented on README.md
> +Introduciendo make help o task help te muestra los comandos necesarios muy sencillos. Por ejemplo make build o task build compila el proyecto e ingresa el bin en la carpeta ./bin
Solucionado en [5463cd0](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/23/commits/5463cd0b9d37479e511e9cd598c8e5adb9b6a80d)

2023-11-17 08:57 UTC, JJ approved these changes
👍

2023-11-17 09:14 UTC, merged