Objetivo 4
carlosservi/Asistente_Ruta_Camioneros pull request #42
Opened 2023-11-26 11:25 UTC by carlosservi

Lista de comprobación:

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-27 09:48 UTC, PabloBarTo approved these changes
Buenas! Yo lo veo todo en general bastante bien. Lo que sí me ha faltado ver son unos criterios al elegir el test runner que aunque hayas elegido el que trae el propio go, no estarían mal unos criterios que justifiquen aun más la elección. Pero vaya se nota que hay un gran trabajo detrás 👍

2023-11-27 09:48 UTC, PabloBarTo commented on docs/metodologia_y_herramientas_test.md
> +-Mejora la comunicación entre desarrolladores, testers, usuarios y la dirección.
Estas dos líneas no siguen el mismo formato que la que tienen justo encima.

2023-11-27 14:26 UTC, carlosservi commented on docs/metodologia_y_herramientas_test.md
> +-Mejora la comunicación entre desarrolladores, testers, usuarios y la dirección.
Muchas gracias por la ayuda y por los comentarios. He añadido los criterios para la elección de las herramientas y he arreglado el formato de las líneas. Solucionado en [7f56df0](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/7f56df082528db22e7083cf460db11e77c7a9553)
Muchas gracias por todo

2023-11-27 15:49 UTC, PabloBarTo requested changes
Te he dejado otro comentario que yo creo que puede ser de utilidad para aprobar este objetivo.

2023-11-27 15:49 UTC, PabloBarTo commented on docs/metodologia_y_herramientas_test.md
> +- Facilidad de uso
Este criterio yo lo cambiaría o directamente lo quitaría porque según el fichero de errores frecuentes no es un criterio válido ya que no es algo que tú puedas medir como tal con un número o con un porcentaje.

2023-11-29 15:54 UTC, carlosservi commented on docs/metodologia_y_herramientas_test.md
> +- Facilidad de uso
Solucionado en [845a25f](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/845a25f198a54c3574cd104bd05ae43289e8245c)
Muchas gracias por todo compañero

2023-11-29 18:40 UTC, PabloBarTo approved these changes
Yo lo veo ya correcto. Espero que mi review haya servido para estar un paso más cerca de aprobar este objetivo. Suerte!

2023-12-01 11:15 UTC, JJ commented on iv.yaml
>    fichero: "Taskfile.yaml"
Esto te va a dar error en objetivos sucesivos, porque es en mayúscula. Si lo cambias ya, eso que te ahorras.

2023-12-01 11:16 UTC, JJ commented on src/main/main.go
> +func main() {
¿Por qué usas un main?

2023-12-01 11:16 UTC, JJ commented on src/route/route.go
> +			if (sumaDescansos + suma + int(route.RouteMinutesTimes[i])) <= int(route.TotalMinutesDistance) {
Estás haciendo la misma conversión dos veces. ¿por qué no lo almacenas como entero directamente?

2023-12-01 11:17 UTC, JJ commented on src/route/route.go
> +				// fmt.Println("No se para en: ", parada)
Por favor, borra directamente lo que no uses.

2023-12-01 11:17 UTC, JJ commented on src/route/util.go
> +	start, _ := time.Parse(time.RFC3339, horario.StartTime)
Si tienes que parsear cada vez, ¿por qué no lo almacenas en ese formato?

2023-12-02 09:23 UTC, carlosservi commented on .gitignore
> +/bin
Solucionado en [fff6ae7](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/fff6ae7fdd73b3c63b32c689ac60a462a220bee0)

2023-12-02 09:29 UTC, carlosservi commented on Taskfile.yaml
> +  #     - echo "task test: Ejecuta los tests."
Eso fue porque empezo a dar error y no se porque ya que antes si funcionaba y por eso lo comenté y me olvidé de eliminarlo. Ya está limpio el código. Solucionado en [edd26f4](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/edd26f48aba4d18d110cfbac66a94696e7912c2a)

2023-12-02 10:26 UTC, carlosservi commented on docs/metodologia_y_herramientas_test.md
> +- Test runner.- Golang incluye su propio framework de test en Go packages, siendo también el estándar y proporcionando muchas funcionalidades cómo por ejemplo, 'fstest' que sirve para file systems, '
Solucionado en [3ffecf4](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/3ffecf4a08178e3330a367e23618662de18f2efc)

2023-12-02 10:27 UTC, carlosservi commented on docs/metodologia_y_herramientas_test.md
> +- Flexibilidad y extensibilidad
Solucionado en [3ffecf4](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/3ffecf4a08178e3330a367e23618662de18f2efc)

2023-12-02 10:36 UTC, carlosservi commented on src/main/main.go
> +func main() {
Tiene toda la razón, simplemente lo cree para ir haciendo pruebas mientras hacía el algoritmo, pero no tiene ningún sentido que esté en este momento. Solucionado en [5856b43](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/5856b435b96f101afdb360a1c86d2bb71ad858f9)

2023-12-02 11:39 UTC, carlosservi commented on src/route/route.go
> +			if (sumaDescansos + suma + int(route.RouteMinutesTimes[i])) <= int(route.TotalMinutesDistance) {
Solucionado en [b8413e3](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/b8413e390f25819a798b86fedea5386710a602a2). He puesto todos a formato int para evitar casting innecesarios

2023-12-02 11:39 UTC, carlosservi commented on src/route/route.go
> +				// fmt.Println("No se para en: ", parada)
Solucionado en [edd26f4](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/42/commits/edd26f48aba4d18d110cfbac66a94696e7912c2a)

2023-12-02 11:40 UTC, carlosservi commented on src/route/util.go
> +	start, _ := time.Parse(time.RFC3339, horario.StartTime)
Lo he probado de todas las maneras posibles, pero no es posible al serializar el json que me lo convierta directamente en un Time, por lo que no me ha quedado más remedio que hacerlos string y crear este parseo sólo en esta función que si necesita comprobar el horario, lo demás funciona sin problema con strings.

2023-12-02 11:58 UTC, carlosservi commented
@JJ He realizado todo los cambios que he podido de los comentarios que me ha hecho, además le he dado un repasillo a todo para que funcione correctamente y se vea lo mejor posible. Listo para revisión.

2023-12-02 18:04 UTC, JJ commented
Los mensajes de commit son bastante explicativos y eso está bien, pero si los limitas a 50 caracteres en la primera línea son más fáciles de leer.

2023-12-02 18:06 UTC, JJ approved these changes
Gracias por haber hecho todos los cambios. Buen trabajo.

2023-12-02 18:15 UTC, merged