[IV-23-24] Objetivo 5
carlosservi/asistente_ruta_camioneros pull request #53
Opened 2023-12-14 11:54 UTC by carlosservi

Lista de comprobación:

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2023-12-15 08:26 UTC, carlotiii30 requested changes
Buenas, en general veo bien el objetivo, sin embargo, no he podido descargarme la imagen para testearla.

2023-12-15 08:26 UTC, carlotiii30 commented on README.md
> +También tenemos el contenedor publicado en [Docker Hub - carlosservi](https://hub.docker.com/repository/docker/carlosservi/asistente-ruta-camioneros/):
El enlace a Docker Hub no funciona.

2023-12-15 08:47 UTC, Enaraque commented
También hay que tener en cuenta las buenas prácticas a la hora de escribir los commits para que cada mensaje de commit esté asociado a un determinado issue, así como tener en cuenta la longitud del mensaje principal del commit.

2023-12-15 08:53 UTC, carlosservi commented on README.md
> +También tenemos el contenedor publicado en [Docker Hub - carlosservi](https://hub.docker.com/repository/docker/carlosservi/asistente-ruta-camioneros/):
Toda la razón, he tenido que cambiarlo al final y se me pasó cambiarlo ahí. Solucionado en [437bb1f](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/437bb1f3039530c4c2ece0d498bb5ec01418345a)

2023-12-15 09:06 UTC, carlosservi commented on Dockerfile
> +USER user
Solucionado en [4fb2b82](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/4fb2b828623a68db5176db3fefb9447fd86f396f)

2023-12-15 09:06 UTC, carlosservi commented on Dockerfile
> +CMD ["test"]
Solucionado en [4fb2b82](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/4fb2b828623a68db5176db3fefb9447fd86f396f)

2023-12-15 09:10 UTC, carlosservi commented on Dockerfile
> +
Solucionado en [4fb2b82](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/4fb2b828623a68db5176db3fefb9447fd86f396f)

2023-12-15 09:36 UTC, pluque01 reviewed
Hola!
Yo lo veo muy completo, pero te he comentado un par de cosas que puedes mejorar.
Ánimo! :))

2023-12-15 09:36 UTC, pluque01 commented on Dockerfile
> +RUN go mod download && go install github.com/go-task/task/v3/cmd/task@latest
En principio, USER gouser no tiene permisos para copiar en la carpeta `/app/test`. Es mejor si haces el COPY en otra carpeta como puede ser `/app`. Ahía también puedes ejecutar el go mod download y el install y luego cambiar el directorio a `/app/test`.
También se explica en los [errores frecuentes del objetivo](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-5.md).

2023-12-15 09:36 UTC, pluque01 commented on docs/eleccion_imagen_docker.md
> +- Seguridad: Que no tenga vulnerabilidades graves.
Veo que has mencionado el criterio de seguridad, pero yo entonces pondría puntuaciones de Snyk Advisor en las opciones a tener en cuenta.

2023-12-15 10:35 UTC, carlosservi commented on Dockerfile
> +FROM golang:1.21-alpine
Perfecto, muchas gracias por la ayuda. He cambiado la imagen base para utilizar debian-slim que es una versión de debian mucho mas liviana y he instalado las herramientas necesarias. Solucionado en [6b1f6c1](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/6b1f6c1ff6bbd78550943dd3d301e549e5a38a22)

2023-12-15 10:35 UTC, carlosservi commented on docs/eleccion_imagen_docker.md
> +- Otros SO: Podemos elegir entre imagenes oficiales de otros Sistemas Operativos, sería algo similar a Alpine, el problema reside en el tamaño que aunque existen versiones slim (ligeras) normalmente
Solucionado en [6b1f6c1](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/6b1f6c1ff6bbd78550943dd3d301e549e5a38a22)

2023-12-15 12:59 UTC, carlosservi commented on Dockerfile
> +FROM golang:1.21-alpine
Había algunos errores en el dockerfile que ya he solucionado en [d171d17](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/d171d17b99caa19a23b73ca93dc796be6cc99473). Gracias

2023-12-15 12:59 UTC, carlosservi commented on Dockerfile
> +RUN go mod download && go install github.com/go-task/task/v3/cmd/task@latest
Muchas gracias por la ayuda. Lo he solucionado en [d171d17](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/d171d17b99caa19a23b73ca93dc796be6cc99473)

2023-12-15 13:57 UTC, carlosservi commented on docs/eleccion_imagen_docker.md
> +- Seguridad: Que no tenga vulnerabilidades graves.
No he conseguido encontrar las puntuaciones que les proporciona Snyk, solamente consigo encontrar las vulnerabildiades detectadas, por lo que lo he rellenado con las vulnerabilidades. Solucionado en [a5c42a3](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/a5c42a34e5e4f0a212a1526b2a42e3a15282b632)

2023-12-15 15:04 UTC, pluque01 commented on docs/eleccion_imagen_docker.md
> +- Seguridad: Que no tenga vulnerabilidades graves.
También es buena alternativa :))

2023-12-16 08:57 UTC, carlosservi commented on docs/eleccion_imagen_docker.md
> +- Seguridad: Que no tenga vulnerabilidades graves.
Si lo ves todo correctamente, apruebame el PR porfa :+1:

2023-12-16 10:12 UTC, carlotiii30 approved these changes
Yo creo que ya está listo.

2023-12-16 11:08 UTC, pluque01 approved these changes
Yo lo veo listo para revisión :))

2023-12-16 13:05 UTC, Enaraque commented
Por lo general lo veo bien. Intenta marcar como resueltos los comentarios que vas solucionando para mantener un poco de orden en la pr. También intentaría crear issues los cuales describan el problema a resolver, no solo uno general en el caso del #54. Quitando estas cosillas, el código lo veo listo. Buen trabajo :rocket:

2023-12-16 13:05 UTC, Enaraque approved these changes

2023-12-16 14:33 UTC, carlosservi commented
Gracias compañer@s. @JJ Listo para revision

2023-12-17 09:26 UTC, JJ requested changes
Por favor, consulta los [errores comunes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-5.md), sobre todo a partir del primero, y trata de evitarlos.
Por otro lado, también conviene que borres los ficheros que has usado en la construcción cuando ya no los necesites.

2023-12-17 09:26 UTC, JJ commented on Dockerfile
> +FROM debian:stable-slim AS final
¿Seguro que es la buena práctica poner esto aquí y no justo antes de la orden `COPY`?

2023-12-17 09:26 UTC, JJ commented on Dockerfile
> +RUN adduser --disabled-password -u 1001 gouser
¿Has considerado poner todas las órdenes iguales en secuencia en una sola?

2023-12-17 09:26 UTC, JJ commented on docs/eleccion_imagen_docker.md
> +- Debian-slim: Existe una imagen de Debian slim que pesa menos ya que incluye el SO más básico, que incorporandole las herramientas necesarias sería mucho mas liviano que la imagen Debian normal. No
Desde el principio os comenté que teníais al menos que considerar otras imágenes, aunque fuera para conocer qué es lo que hay.

2023-12-17 17:42 UTC, carlosservi commented on Dockerfile
> +FROM debian:stable-slim AS final
Solucionado en [b2b635c](https://github.com/carlosservi/asistente_ruta_camioneros/pull/53/commits/b2b635c07505d1b2c89fe14baaeac313f8de2ddf)

2023-12-17 17:42 UTC, carlosservi commented on Dockerfile
> +RUN adduser --disabled-password -u 1001 gouser
Solucionado en b2b635c

2023-12-17 17:51 UTC, carlosservi commented on docs/eleccion_imagen_docker.md
> +- Debian-slim: Existe una imagen de Debian slim que pesa menos ya que incluye el SO más básico, que incorporandole las herramientas necesarias sería mucho mas liviano que la imagen Debian normal. No
Solucionado en d678fb7

2023-12-17 17:52 UTC, carlosservi commented
@JJ He intentado mejorar los puntos que usted me ha comentado. Listo para revisión.

2023-12-17 18:12 UTC, JJ approved these changes
:+1:  Y muchísimas gracias a @Enaraque, @pluque01 y @carlotiii30  por la ayuda prestada.

2023-12-17 18:12 UTC, JJ commented on Dockerfile
> +ENV PATH=$PATH:$GOPATH/bin
Estos también puedes ponerlos en uno solo, aunque no van a tener demasiada influencia en el tamaño final de la imagen.

2023-12-22 11:55 UTC, merged