[IV-23-24] Objetivo 1
carlosservi/Asistente_Ruta_Camioneros pull request #6
Opened 2023-09-21 10:08 UTC by carlosservi

Sobre los milestones

* [v] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [v] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [v] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [v] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [v] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [v] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [v] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [v] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [v] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [v] ¿El milestone 0 es mínimo *y* viable?
* [v] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [v] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Sobre las historias de usuario

* [v] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [v] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [v] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [v] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-21 12:56 UTC, JJ requested changes
Aparte de lo dicho, en las historias de usuario tienes que explicar el contexto y los datos disponibles, sobre todo para asegurarte de que realmente estás aplicando una lógica de negocio que no sea simplemente poner el área de descanso más cercana que ya esté en la ruta. Si hay que desviarse de la ruta u otro tipo de cosas, son variables que tendrás que tener en cuenta.

Como he dicho en clase, las HUs son herramientas reales para ponerse a trabajar, y en las HUs tienes que expresar los diferentes requisitos, también quizás en complejidad creciente. En la descripción has hablado por ejemplo de circunstancias atmosféricas. NO sé qué tienen que ver con el problema, pero si tienen, tendrás que tenerlas en cuenta en una historia de usuario. 

Por último, permíteme que insista en el tema de tener conocimiento personal del problema. En este caso, tendrás que intentar tener datos más o menos reales sobre las carreteras, la duración de los viajes y demás, todo ello *sin tener en cuenta ningún dato físico que no vas a poder captar de los camiones*.

Si es necesario cambiar ligeramente la descripción del problema en las historias de usuario, hazlo.

2023-09-21 12:56 UTC, JJ commented on docs/historias_de_usuario.md
> +Antonio necesita que el sistema esté disponible para usarlo él y todos sus compañeros, desde cualquier lugar y con cualquier dispositivo.
Esto es un requisito funcional, no una historia de usuario.

2023-09-21 12:56 UTC, JJ commented on docs/milestones.md
> +Tenemos que trabajar en una interfaz gráfica básica que le permita al usuario introducir el origen y el destino de la ruta, una vez lo introduzca le mostraremos por pantalla un mapa con una línea señ
No se puede trabajar en la interfaz gráfica antes de cualquier otra cosa, especialmente no en esta asignatura. Por favor, ten en cuenta que tienes que ir construyendo capas de abstracción, y la primera es siempre un modelo del problema.

2023-09-24 16:59 UTC, carlosservi commented
@JJ Realizados cambios en Historias de usuario y Milestones.

2023-09-26 15:34 UTC, carlosservi commented
@JJ Cambios realizados en milestones. Listo para revisión.

2023-09-26 15:42 UTC, JJ requested changes
Me temo que, tras varias iteraciones, no termino de ver qué hay de lógica de negocio compleja en la elección de las áreas de descanso. Sólo tienen un parámetro que las describa: distancia. Se trata de maximizar la distancia hasta el área de descanso dentro de las restricciones. Es simplemente calcular un máximo, lo que no representa una lógica de negocio compleja.

Me temo que vas a tener que plantear otro problema. Sin una lógica de negocio suficientemente compleja, es imposible seguir adelante en esta asignatura, porque es imposible aprender la aplicación de diferentes técnicas  sobre algo que sea excesivamente simple.

Para hacerlo, lo mejor es que vuelvas a enviar el objetivo 0 en un PR diferente, en la página del objetivo cero. No invalida que lo tengas ya superado, pero no veo otro remedio a este problema. Siento haberlo aceptado en su momento, pero ya te advertí el tema de las áreas de descanso repetidamente.

2023-09-26 17:45 UTC, JJ commented
Estoy pensando y una forma de que esto sirviera sería optimizar la hora de salida para maximizar las horas que se está sin parar, de forma que se aprovecharan lo máximo las horas continuas en las que se está trabajando y las áreas de descanso estuvieran lo más cerca posible de las horas de descanso. Sí sería un problema de optimización, porque dentro del margen de horas de salida (u horas de llegada), tendrías margen para aplicar algún algoritmo de optimización. En todo caso, tendrías que tener en cuenta qué retraso introduce  cada área de descanso en la ruta, aunque podría ser siempre el mismo. También en las rutas habría qeu tener en cuenta a la hora que se llegue si están abiertas o no.

Una variación, u otra posibilidad, es dar la hora de llegada y en función de eso establecer la hora de salida. Por favor, piénsate si alguna de esas cosas tiene sentido y en ese caso no hace falta que pienses en un nuevo problema para el objetivo 0, cambia este y listo. Si no, algún problema similar donde haya algo que optimizar y aplicar un algoritmo que tenga cierta complejidad para hallar ese óptimo.

2023-09-26 20:00 UTC, carlosservi commented
@JJ No había visto éste último mensaje y ya he preparado otro posible proyecto, he actualizado el PR en el enlace del objetivo 0, si no ve bien el otro, entonces intento mejorar éste.

2023-09-26 20:19 UTC, JJ commented
Lo que tú prefieras. Si ves esto que te digo viable, dejamos el otro.

2023-09-28 09:21 UTC, carlosservi commented
@JJ He realizado los cambios propuestos, he introducido los retrasos de las distintas áreas de servicio y el sistema le indicará la hora de salida óptima.

2023-09-28 10:40 UTC, JJ requested changes
Las HUs están prácticamente completas (salvo detalles), pero los milestones tienes que expresarlos un poco mejor, sobre todo teniendo en cuenta que se debe tratar de productos mínimamente viables y que en estos se sigue prácticamente en todos los casos la misma secuencia para el 0 y el 1

2023-09-28 10:40 UTC, JJ commented on docs/milestones.md
> +    Con todo ello el sistema debe ser capaz de establecer una hora de salida óptima y las paradas idóneas para llegar al destino a tiempo.
Si no tienes un modelo del problema, no puedes implementar la lógica de negocio. Por eso en la lista de comprobación se habla de milestones intermedios (que no son código testeado)

2023-09-28 10:40 UTC, JJ commented on docs/milestones.md
> +    - Documento detallado del modelo del problema.
Un documento no es un producto viable.

2023-09-28 10:40 UTC, JJ commented on docs/milestones.md
> +    - Codificar el algoritmo de optimización de rutas que tenga en cuenta los tiempos de descanso obligatorios, las posibles estaciones de servicio dónde parar, calculando los posibles retrasos produ
Si aquí implementas el algoritmo, ¿qué es establecer la salida óptima que habías puesto en el anterior?

2023-09-28 10:40 UTC, JJ commented on docs/historias_de_usuario.md
> +El sistema debe permitir a Carlos y Marta ingresar el número de ruta y la hora de llegada requerida.
¿Los cambios de conductor los pueden hacer en cualquier sitio? ¿Introducen también un retraso en la ruta?

2023-09-29 07:29 UTC, carlosservi commented
@JJ Listo para revisión

2023-09-29 07:42 UTC, carlosservi commented on docs/milestones.md
> +    - Codificar el algoritmo de optimización de rutas que tenga en cuenta los tiempos de descanso obligatorios, las posibles estaciones de servicio dónde parar, calculando los posibles retrasos produ
Resuelto en commit [0dfbe21](https://github.com/carlosservi/Asistente_Ruta_Camioneros/pull/6/commits/0dfbe2137446311b9330c571f8121e88178ffb81)

2023-09-29 07:46 UTC, JJ approved these changes
👍 
Gracias por el trabajo realizado. Habría sido un poco más correcto que lo pusieras en el *título* del milestone, pero así me vale.

2023-09-29 07:50 UTC, merged