[IV-23-24] Objetivo 6
carlosservi/Asistente_Ruta_Camioneros pull request #61
Opened 2023-12-26 16:39 UTC by carlosservi

Closes #57 
Closes #58 
Closes #59 

Lista de Comprobación:

* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   dellenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-12-31 09:00 UTC, JJ requested changes
En general está bien, el problema es que no has examinado demasiadas alternativas y además hay errores en la descripción de las alternativas que sí has examinado. Conviene ser muy preciso en este tipo de documentación, porque se trata de justificar decisiones que pueden ser fundamentales para una empresa.

2024-01-02 17:27 UTC, carlosservi commented on docs/eleccion_CI.md
> +- Circle CI.- No se puede integrar con Github por el momento, Es compatible con Golang y Docker. Tiene un plan gratuito para un tiempo especifico al mes, por lo que podría ser útil para proyectos en
No había explicado bien el problema de Circle, el problema es que por el momento no puede conectarse con Api Checks, ya lo he puesto bien y he puesto un enlace a la documentación donde lo dicen. También he añadido otra opción mas de CI. Solucionado en [716fa84](https://github.com/carlosservi/asistente_ruta_camioneros/pull/61/commits/716fa84251457a89c0395578896dab1e5cc02804)

2024-01-02 17:28 UTC, carlosservi commented
@JJ  Listo para revisión

2024-01-02 18:24 UTC, JJ requested changes
Me temo que no has subido la configuración de TeamCity. Si es un error en la documentación porque no es eso lo que querías decir, corrígelo, por favor. Si es que efectivamente no lo has subido, hazlo, por favor.

2024-01-02 18:24 UTC, JJ commented on docs/eleccion_CI.md
> +Por el momento descarto Circle CI ya que por el momento no puede usar la API Github Checks por lo que no me sirve, voy a probar las otras 3 opciones y decidiré.
¿Qué ocurre con la checks API?

2024-01-12 10:32 UTC, carlosservi commented on docs/eleccion_CI.md
> +Por el momento descarto Circle CI ya que por el momento no puede usar la API Github Checks por lo que no me sirve, voy a probar las otras 3 opciones y decidiré.
He cambiado TeamCity porque ahora me fallaba, lo he cambiado por AppVeyor que es muy sencillo e intuitivo. He quitado esa parte de la checks API simplemente no lo pruebo y ya está. Solucionado en [3316777](https://github.com/carlosservi/asistente_ruta_camioneros/pull/61/commits/3316777ee0371b5c1e0ba32ff8cbda62481fec70)

2024-01-12 10:55 UTC, carlosservi commented
@JJ Listo para revisión

2024-01-12 12:18 UTC, JJ commented
El "Checks API" lo que hace es que los resultados aparezcan en "All checks", como arriba. Ahora sólo aparecen los de GitHub. ¿Tienes que activar algo en alguno de los otros?

2024-01-12 12:19 UTC, JJ commented
¿Seguro que tienes AppVeyor bien configurado? Dice "project not found or access denied".

2024-01-12 12:21 UTC, JJ requested changes
Parece que Semaphore CI ha pasado el periodo de prueba (y hay una configuración de Ubuntu un poco rara) y AppVeyor está dando errores, ¿no?

2024-01-12 12:21 UTC, JJ commented on .semaphore/semaphore.yml
> +    os_image: ubuntu2004
¿Ubuntu 2004 es correcto?

2024-01-12 12:21 UTC, JJ commented on docs/eleccion_CI.md
> +- Semaphore CI.- Se puede integrar con Github, no es gratuito pero tiene un periodo de prueba de 14 días. Admite el lenguaje Golang. Es integrable con Docker y está disponible online. Además tiene un
Supongo que ya pasó, ¿no?

2024-01-15 09:36 UTC, carlosservi commented on .semaphore/semaphore.yml
> +    os_image: ubuntu2004
Si es correcto o por lo menos así funcionaba. Está usando la versión Ubuntu 20.04, el problema es que ha caducado el tiempo de prueba

2024-01-15 09:37 UTC, carlosservi commented on docs/eleccion_CI.md
> +- Semaphore CI.- Se puede integrar con Github, no es gratuito pero tiene un periodo de prueba de 14 días. Admite el lenguaje Golang. Es integrable con Docker y está disponible online. Además tiene un
Sí ya ha caducado.

2024-01-15 09:40 UTC, JJ commented on .semaphore/semaphore.yml
> +    os_image: ubuntu2004
Ah, ok, especificaba así la versión.

2024-01-15 09:40 UTC, JJ approved these changes
:+1:

2024-01-15 09:42 UTC, merged